spring.application.name=pokedex-backend

# H2 Console - Acesso pelo navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Permite que o console apareça dentro do navegador sem ser bloqueado
spring.queries.hibernate.generate_statistics=true
spring.h2.console.settings.trace=true
spring.main.allow-circular-references=true

# Configuração do Banco de Dados na Memória
spring.datasource.url=jdbc:h2:mem:pokedexdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate - Cria as tabelas automaticamente
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
